// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDSlCvqkcaSuiS62Rz2vjc-fGsCpCVRgSI',
    appId: '1:250033235653:web:856194f886f1032650b2ac',
    messagingSenderId: '250033235653',
    projectId: 'reciubate',
    authDomain: 'reciubate.firebaseapp.com',
    storageBucket: 'reciubate.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD16i1IVvdWK0rt-EFbqY3iiicgJr9ABe0',
    appId: '1:250033235653:android:923dface2040f39650b2ac',
    messagingSenderId: '250033235653',
    projectId: 'reciubate',
    storageBucket: 'reciubate.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDmAKSk6wP-auFRj8GrgG-pcz5kWF5MpLg',
    appId: '1:250033235653:ios:92e48b23805be79850b2ac',
    messagingSenderId: '250033235653',
    projectId: 'reciubate',
    storageBucket: 'reciubate.firebasestorage.app',
    androidClientId: '250033235653-u3t84m1sn8ep7uufqkeippohc8qfmuvn.apps.googleusercontent.com',
    iosClientId: '250033235653-07fd0hdmoj71mfu06sl1f1blfmhfsveb.apps.googleusercontent.com',
    iosBundleId: 'com.example.reciUbate',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDSlCvqkcaSuiS62Rz2vjc-fGsCpCVRgSI',
    appId: '1:250033235653:web:d5284a95ae91913950b2ac',
    messagingSenderId: '250033235653',
    projectId: 'reciubate',
    authDomain: 'reciubate.firebaseapp.com',
    storageBucket: 'reciubate.firebasestorage.app',
  );

}